name: do_spaces_flutter
description: A Flutter App using Digital Ocean Spaces

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2021.02.20+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.7.0
  cloud_functions: ^0.9.0
  # single image picker
  image_picker: ^0.6.7+22
  # multiple image pickers
  image_pickers: ^1.0.8+7
  http: ^0.12.2
  flutter_bloc: ^6.1.2
  equatable: ^1.2.6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
